 # Using Python Numpy and Pandas modules

In [1]:
# I will use Numpy and Pandas Modules
import numpy as np
import os
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
from pandas import Series, DataFrame
import pandas as pd
np.set_printoptions(precision=4)

# Displaying the data sets

In [15]:
titles=pd.read_table('titles.tsv') # contains 'movie_id', primary title ('title'), & 'production year' of many movies
directors=pd.read_table('directors.tsv') # contains 'person_id', 'movie_id', 'name', and 'gender' of directors.
actors=pd.read_table('actors.tsv')
titlesAKA=pd.read_table('titles_AKA.tsv')
namesAKA=pd.read_table('names_AKA.tsv')

In [8]:
titles

,movie_id,title,production_year
0,7,#1 Beauty Nail Salon,2014
1,9,#1 Serial Killer,2013
2,11,#1137,2015
3,14,#2 Chick,2014
4,29,#50Fathers,2015
5,33,#707,2014
6,37,#99,2015
7,38,#am/pm,2016
8,42,#Anatomy of the Romantic Comedy,2016
9,43,#AndJusticeForAll: The Rhetoric of a Post-Raci...,2016
10,47,#AskAKid,2014
11,48,#Askhermore,2015
12,53,#BeRobin the Movie,2015
13,54,#BeYourself,2015
14,60,#Blondepeopleproblems,2014
15,66,#chicagoGirl: The Social Network Takes on a Di...,2013
16,67,#Click,2015
17,73,#conniesflat,2013
18,75,#Deception,2013
19,76,#DemocraciaReal,2013
20,79,#Done!,2015
21,80,#DoTheMileyCyrus,2014
22,81,#DreamRideLA,2015
23,82,#EndTheMommyWars,2015
24,85,#ExposeTheseHoes,2014
25,87,#Fila,2013
26,90,#Fix,2013
27,91,#Flora63,2016
28,95,#Generation Bieber,2015
29,96,#GirlCrush,2015
...,...,...,...
76342,880611,Överliggaren,2014
76343,880623,Özür Dilerim,2013
76344,880678,Última Parada 174,2008
76345,880685,Última Transmisión,2013
76346,880713,Último sueño,2013
76347,880719,Últimos días en La Habana,2016
76348,880751,Útitárs,2014
76349,880766,Ü.N.K.,2013
76350,880848,Ülkücüler,2012
76351,880865,ÜnOfficially Yours,2012
76352,880876,Üvegtigris 3.,2010
76353,880888,Üç Adam,2014
76354,880917,"Üç, Iki, Bir... Kestik!",2014
76355,880929,Þetta Reddast,2013
76356,880930,Þrestir,2015
76357,880932,Þrot,2015
76358,880941,å gå videre,2014
76359,880942,ça goûte le ciel,2014
76360,883899,Don Quixote: The Ingenious Gentleman of La Mancha,2015
76361,927634,Selling Stupid,2014
76362,945431,Noah's Ark,2014
76363,945777,State of Delinquency,2015
76364,958486,Les mecs n'ont pas de chance,2015
76365,1036135,Ellis,2015
76366,1131388,Solstice,2015
76367,1148950,Merlot,2015
76368,1180146,Syncretic Noise,2015
76369,1249695,Once Again,2016
76370,1339045,Perimeter,2016
76371,1710554,The Other Side of the Wind,2016

In [9]:
directors

       person_id  movie_id                      name gender
0        3846082    327435    &Oumlzkul, Ahmet Salih    NaN
1        3517999    120953      'Dada' Pecori, Diego    NaN
2        3518000     73095              'Kusare, Mak    NaN
3        3846084     21452              'Kusare, Mak    NaN
4        3518003    431038          't Hooft, Albert    NaN
5            197    863899               --, An��nimo      m
6        3518008    538610               --, Broncos    NaN
7        3846088    425074                  --, Nysu    NaN
8        3518010    523967             ., Brickhouse    NaN
9        3518011    355903                 ., Crobin    NaN
10           251    340420                ., Slavina      m
11       3846092    327621                 ., Wooloo    NaN
12           269    376706                   1, Todd      m
13       3518019    761865                 A, Salman    NaN
14           688      6411                A., Sergey      m
15           688     57231                A., Sergey      m
16           688     77006                A., Sergey      m
17           688     81591                A., Sergey      m
18           688     94939                A., Sergey      m
19           688    127010                A., Sergey      m
20           688    351419                A., Sergey      m
21           688    376189                A., Sergey      m
22           688    423513                A., Sergey      m
23           688    506097                A., Sergey      m
24           688    562348                A., Sergey      m
25           688    686397                A., Sergey      m
26           688    728164                A., Sergey      m
27           688    801723                A., Sergey      m
28           688    807851                A., Sergey      m
29           746     87090               A.M., Tyler      m
...          ...       ...                       ...    ...
82792    3960450    449593              ��zel, Tarkan    NaN
82793    3845967    384180                ��zge, Asli    NaN
82794    3960454    838705             ��zg��ner, ��zge    NaN
82795    3845972    495269            ��zg��r, Marleen    NaN
82796    2272747    588321        ��zkul, Ahmet Salih      m
82797    3960457    602297              ��zlevi, Erol    NaN
82798    3845988    689727              ��zmen, Alkim    NaN
82799    3845990     32315              ��zmen, Mahur    NaN
82800    3845994    449565       ��ztekin, Mehmet Ada    NaN
82801    3846000    314705            ��zt��rk, B��lent    NaN
82802    3960465     32315               ��zuyar, Ali    NaN
82803    2272892    231286           ��zyurtlu, Caner      m
82804    2272892    868816           ��zyurtlu, Caner      m
82805    3846008    499767           ��z��ift��, G��rhan    NaN
82806    3846009    510259          ��z��ift��i, G��rhan    NaN
82807    2273025      3809        ��stergaard, Anders      m
82808    2273025    113950        ��stergaard, Anders      m
82809    2273069    603083     ��strem, Andreas Amdal      m
82810    3846032    792215         ��vergaard, Anders    NaN
82811    3846036    806175            ��vredal, Andr��    NaN
82812    3846036    809242            ��vredal, Andr��    NaN
82813    3846039    659468              ��beda, Joant    NaN
82814    3846049    611313               ��nal, Haluk    NaN
82815    2273222     60003                ��nal, ��mit      m
82816    2273222    497622                ��nal, ��mit      m
82817    2273242    126684                ��nl��, Onur      m
82818    2273242    562886                ��nl��, Onur      m
82819    2273242    879636                ��nl��, Onur      m
82820    3960483    880932  ��orvar��arson, Dav���� Go��i    NaN
82821    3960486      4309           �� B��le, Jacques    NaN

[82822 rows x 4 columns]

In [10]:
actors

        person_id  movie_id                              name gender
0               4     82700                        $hort, Too      m
1               4    666764                        $hort, Too      m
2              20    430190       'babeepower' Viera, Michael      m
3              29     42785             'Casper' Brown, Jesse      m
4              29     72351             'Casper' Brown, Jesse      m
5              29     81242             'Casper' Brown, Jesse      m
6              29    371988             'Casper' Brown, Jesse      m
7              29    664920             'Casper' Brown, Jesse      m
8              34    796332               'Colibri'Viera, Gil      m
9              65     16156              'Fingerz' Esbai, Ali      m
10             70    449572    'Ghetto Bird' Bahena, Gilberto      m
11             73    842051             'Hos' Bearzi, Marcelo      m
12             75    806257              'Illy' Liban, Ellias      m
13             80    183926             'Jazz' Jasmer, Andrew      m
14             85    513587          'Koolout' Starks, Johnny      m
15             85    584776          'Koolout' Starks, Johnny      m
16             89    348706              'Little Kato', Chris      m
17             92    874361             'Mad Dog' Adams, Mike      m
18             97    352935     'McGillicuddy' Johnson, Hildy      m
19            100     73878            'Monkey' Stevens, Neal      m
20            100    639920            'Monkey' Stevens, Neal      m
21            100    738663            'Monkey' Stevens, Neal      m
22            121    126865           'Shotgun' Smith, Andrew      m
23            126     81242     'Spax' Szulc-Vollmann, Rafael      m
24            127    357893       'Stake' Morton III, Michael      m
25            140      7057                't Hout, Rogier in      m
26            140    115481                't Hout, Rogier in      m
27            145    175092   'The Carpenter' Mansoori, Harry      m
28            150    321829  'Thundakat' Abrams, Andre-Julius      m
29            152     81242           'Trix' Thompson, Albert      m
...           ...       ...                               ...    ...
741072    3517880    207223                       ��nsal, Tuba      f
741073    3517880    559212                       ��nsal, Tuba      f
741074    3517880    879593                       ��nsal, Tuba      f
741075    3517880    879636                       ��nsal, Tuba      f
741076    3517897    488394                      ��st��n, Serap      f
741077    3517906     90175                    ��upala, Pr��ity      f
741078    3517906    260557                    ��upala, Pr��ity      f
741079    3517906    532032                    ��upala, Pr��ity      f
741080    3517906    629295                    ��upala, Pr��ity      f
741081    3517906    836247                    ��upala, Pr��ity      f
741082    3517909    273743                      ����ok, Sevin��      f
741083    3517909    345234                      ����ok, Sevin��      f
741084    3517915     78535          ��orfinnsd��ttir, Kolfinna      f
741085    3517919    219853          ��orgeirsd��ttir, Katla M.      f
741086    3517919    880218          ��orgeirsd��ttir, Katla M.      f
741087    3517919    880930          ��orgeirsd��ttir, Katla M.      f
741088    3517928    100689         ��orkelsd��ttir, Mar��a Heba      f
741089    3517928    523449         ��orkelsd��ttir, Mar��a Heba      f
741090    3517933    595782          ��orl��ksd��ttir, Linda Sif      f
741091    3517948    362415            ��orvaldsd��ttir, Herd��s      f
741092    3517948    676816            ��orvaldsd��ttir, Herd��s      f
741093    3517951    601512      ��orvaldsd��ttir, Lilja Gu��r��n      f
741094    3517951    864837      ��orvaldsd��ttir, Lilja Gu��r��n      f
741095    3517951    880218      ��orvaldsd��ttir, Lilja Gu��r��n      f
741096    3517963    595780        ����rarinsd��ttir, Lilja N��tt      f
741097    3517963    595782        ����rarinsd��ttir, Lilja N��tt      f
741098    3517966    193270         ����rarinsd��ttir, ��ris Hund      f
741099    3517972    676748             ����risd��ttir, Sara ��sk      f
741100    3517988    880218          ����r��ard��ttir, Lov��sa R��s      f
741101    3517992    676748            ����r��ard��ttir, Steinunn      f

[741102 rows x 4 columns]

In [16]:
titlesAKA

       movie_id                                 alternate_title
0             9                                           Chink
1            95                                    Beliebe This
2           139                                    #Unreal Love
3           139                              #�������������������� ������������
4           139                                     Unreal Love
5           139                               �������������������� ������������
6           145  Your 2nd Life IS My Life: On the Road with O2L
7           173                              Hoy me van a matar
8           173                               Tu color favorito
9           173                                      Vigilantes
10          173                                      Voluntario
11          194                         #TheFutureIsCrowdFunded
12          245                             5 dollari al giorno
13          245                               Five Dollars More
14          245                              Five Dollars a Day
15          260                    Der Sinn des Lebens f��r 9,99
16          263                                      Sellebrity
17          305                  '71: Hinter feindlichen Linien
18          307                                         5-25-77
19          308                                        79 Parts
20          308                                 The Arrangement
21          561   We Should Have This Conversation After Dinner
22          698                                    'Til Sunrise
23          770                            Theatre2Film Project
24          770              Three Hundred and Thirteen Choices
25          772                            (500) giorni insieme
26          772                              500 Days of Summer
27          804               Dishonesty - The Truth About Lies
28          804                                 Slippery Slopes
29          841     Trying to Lose Your Virginity in Highschool
...         ...                                             ...
20094    879518                      Gallipoli: End of the Road
20095    879593                                    Coole Schule
20096    879593                                       The Class
20097    879636                                       The Child
20098    879639                                        Majority
20099    879641            Le Milieu d'une Tres Longue Histoire
20100    879641               The Midpoint of a Very Long Story
20101    879750                                        Daybreak
20102    879818                                  I Remember You
20103    879849                                         D��sir��e
20104    879849                          Madonna: Whore Complex
20105    879849                               Scattered Reality
20106    880048                                     Anniversary
20107    880157                                 In the Fishbowl
20108    880191                              Spooks and Spirits
20109    880193                                             Sty
20110    880217                             Orphans of Eldorado
20111    880218                                         Jitters
20112    880358                                     King's Game
20113    880436                                         Kill Me
20114    880678                                  Endstation 174
20115    880678                                   Last Stop 174
20116    880678             Last Stop 174 - Endstation Hoffnung
20117    880678                                   Rio ligne 174
20118    880685                               Last Transmission
20119    880865                              Unofficially Yours
20120    880876                                    GlassTiger 3
20121    880929                                     Rock Bottom
20122    880930                                        Sparrows
20123    880932                                         Deceive

[20124 rows x 2 columns]

In [17]:
namesAKA

        person_id                           name
0               4                     Short, Too
1              20         Viera, Michael 'Power'
2              29     Brown, Jesse 'BBoy Casper'
3              29            Brown, Jesse Casper
4              29                   Brown, Jesse
5              29                   Casper, Bboy
6              85                 Starks, Johnny
7             100                         Monkey
8             100           Stevens, Neal Monkey
9             100                  Stevens, Neal
10            159                       Bastille
11            269                         Todd-1
12            330                      Boy, Tity
13            330                  Epps, Tauheed
14            493                         G-Unit
15            493      Jackson, Curtis '50 Cent'
16            493      Jackson, Curtis '50 cent'
17            493                Jackson, Curtis
18            493                Johnson, Curtis
19            514                    Tefry, Rich
20            514                Terfry, Richard
21            514                   Terfry, Rich
22            520                   Vuori, Jussi
23            688                       Ar, Serg
24            799            Aabo, Kristoffer E.
25            814                   Aadahl, Eric
26            822                        Pradeep
27        2273565                 Aadusoo, Liisa
28            871            Aagesen, Kristoffer
29            916              Aalam, Abou-Bakre
...           ...                            ...
122587    2273056                Osterud, Bjarne
122588    3846036                 Ovredal, Andre
122589    3517799                ��ien, Ingunn B.
122590    3517799                ��yen, Ingunn B.
122591    3517799                   ��yen, Ingunn
122592    2273132               ��beda, Juan Jos��
122593    2273145                 Zolt��n, Ujv��ri
122594    2273145                 Zolt��n, ��jv��ry
122595    2273182                   Meray, ��lgen
122596    2273182                   ��lger, Meray
122597    2273197                     Un, Memduh
122598    2273197                     ��n, Turhan
122599    3846049                 ��nal, A. Haluk
122600    2273229               G��nd��z, Gazanfer
122601    2273229                Unduz, Gazanfer
122602    2273231                   Uenel, Birol
122603    2273231                   Uenel, Byrol
122604    3517880                    Unsal, Tuba
122605    3517880                   Unsal, Tugba
122606    3517880                   ��nsal, Tugba
122607    3517919  ��orgeirsd��ttir, Katla Margr��t
122608    3517919  ��orvaldsd��ttir, Katla Margr��t
122609    3517919  ����rgeirsd��ttir, Katla Margr��t
122610    2273367     Thorvaldsson, Gudmundur L.
122611    2273367      ��orvaldsson, Gu��mundur I.
122612    2273367         ��orvaldsson, Gu��mundur
122613    3517963                    N��tt, Lilja
122614    3517963    Thorarinsdottir, Lilja Nott
122615    2273396             Thordarson, Ingvar
122616    2273396           ����r��arson, Ingvar H.

[122617 rows x 2 columns]